name: WebDriverIO Tests

on:
  push:
    branches:
      - main

jobs:
  webdriverio:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js 14.x
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Add NodeSource repository
      run: |
        curl -fsSL https://deb.nodesource.com/gpgkey/nodesource.gpg.key | sudo gpg --dearmor -o /usr/share/keyrings/nodesource-archive-keyring.gpg
        echo "deb [signed-by=/usr/share/keyrings/nodesource-archive-keyring.gpg] https://deb.nodesource.com/node_14.x focal main" | sudo tee /etc/apt/sources.list.d/nodesource.list
        echo "deb-src [signed-by=/usr/share/keyrings/nodesource-archive-keyring.gpg] https://deb.nodesource.com/node_14.x focal main" | sudo tee -a /etc/apt/sources.list.d/nodesource.list
        sudo apt-get update
        sudo apt-get install -y nodejs

    - name: Install dependencies with --unsafe-perm and wdio-chromedriver-service
      run: |
        npm install --unsafe-perm --force
        npm install wdio-chromedriver-service --save-dev

    - name: Start Selenium Grid
      run: |
        docker pull selenium/node-chrome:112.0
        docker run -d -p 4444:4444 --name selenium-hub selenium/hub:4.1.0
        docker run -d --link selenium-hub:hub --name selenium-node-chrome selenium/node-chrome:112.0

    - name: Build custom Docker image
      run: docker build -t my-webdriverio-image .

    - name: Run WebDriverIO tests inside Docker container
      run: |
        docker run --rm --link selenium-hub:hub -v $PWD:/app -w /app my-webdriverio-image sh -c "npm install && npx wdio wdio.conf.js --headless --log=ERROR --maxInstances=20"

    - name: Stop Selenium Grid
      run: |
        docker stop selenium-node-chrome
        docker stop selenium-hub
