name: WebDriverIO Tests

on:
  push:
    branches:
      - main

jobs:
  webdriverio:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: actions/setup-docker@v2
      with:
        dockerfile: Dockerfile

    - name: Build and run custom Docker image
      run: |
        docker build -t my-webdriverio-image .
        docker run -d -p 4444:4444 --name selenium-hub selenium/hub:4.1.0
        docker run -d --link selenium-hub:hub --name my-webdriverio-container my-webdriverio-image

    - name: Wait for Selenium Grid to start (adjust as needed)
      run: sleep 30

    - name: Run WebDriverIO tests inside Docker container
      run: |
        docker exec my-webdriverio-container sh -c "npm install && npx wdio wdio.conf.js --headless --log=ERROR --maxInstances=20"

    - name: Stop Selenium Grid and remove containers
      run: |
        docker stop my-webdriverio-container
        docker stop selenium-hub
        docker rm my-webdriverio-container
        docker rm selenium-hub
