name: WebDriverIO Tests

on:
  push:
    branches:
      - main

jobs:
  webdriverio:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js 14.x
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Add NodeSource repository
      run: |
        curl -fsSL https://deb.nodesource.com/gpgkey/nodesource.gpg.key | sudo gpg --dearmor -o /usr/share/keyrings/nodesource-archive-keyring.gpg
        echo "deb [signed-by=/usr/share/keyrings/nodesource-archive-keyring.gpg] https://deb.nodesource.com/node_14.x focal main" | sudo tee /etc/apt/sources.list.d/nodesource.list
        echo "deb-src [signed-by=/usr/share/keyrings/nodesource-archive-keyring.gpg] https://deb.nodesource.com/node_14.x focal main" | sudo tee -a /etc/apt/sources.list.d/nodesource.list
        sudo apt-get update
        sudo apt-get install -y nodejs

    - name: Install dependencies with --unsafe-perm and wdio-chromedriver-service
      run: |
        npm install --unsafe-perm --force
        npm install wdio-chromedriver-service --save-dev

    - name: Set TZ environment variable
      run: |
        export TZ='Pacific/Auckland'
        
    - name: Create folders for Selenium Grid
      run: |
        mkdir -p ~/selenium/grid/folder/reports/json/tmp
        mkdir -p ~/selenium/grid/folder/reports/junit
        
    - name: Run WebDriverIO tests in Selenium Grid
      run: |
        npx wdio wdio.conf.js --headless --log=ERROR --maxInstances=20
